### ISSUE TITLE
TKMM won't open 

### ISSUE THREAD

**Issue by AmyL4** [TKMM-Team/Tkmm#30] opened 2024-07-22 12:56 UTC
I have tried removing tkmm from my computer and re-installing it several times, but every time I can only open the program once, and then when I click on the shortcut I get this error 

![error](https://github.com/user-attachments/assets/196585c6-6723-4811-a7c5-db97e00f91e4)

**Comment by ArchLeaders** [comment] 2024-07-22 16:42
Duplicate of https://github.com/TKMM-Team/Tkmm/issues/29.

Delete `%localappdata%\tkmm\Config.json` to resolve the issue until the next TKMM release.

**Closed by ArchLeaders** 2024-07-22 16:42 UTC
